# Generated by Django 3.2 on 2021-04-30 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reivew',
            new_name='review',
        ),
    ]
